export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_CURRENT_EXPENSE = 'SET_CURRENT';
export const CLEAR_CURRENT_EXPENSE = 'CLEAR_CURRENT';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const FILTER_EXPENSE = 'FILTER_EXPENSE';
export const CLEAR_FILTER_EXPENSE = 'CLEAR_FILTER';
export const SET_ALERT_EXPENSE = 'SET_ALERT';
export const CLEAR_ALERT_EXPENSE = 'CLEAR_ALERT';

export const ADD_INCOMING = 'ADD_INCOMING';
export const DELETE_INCOMING = "DELETE_INCOMING";
export const SET_CURRENT_INCOMING = "SET_CURRENT_INCOMING";
export const CLEAR_CURRENT_INCOMING = "CLEAR_CURRENT_INCOMING";
export const UPDATE_INCOMING = "UPDATE_INCOMING";
export const FILTER_INCOMING = "FILTER_INCOMING";
export const CLEAR_FILTER_INCOMING = "CLEAR_FILTER_INCOMING"

